### PR TITLE
Allow the use of jiff in addition to chrono

### PR DESCRIPTION
**Pull request by bim9262**
I'm interested in using the sunrise crate with a project and would like to use jiff instead of chrono.

This PR adds the ability to enable the use of chrono or jiff as features. (chrono is left as the default).

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -22,21 +22,27 @@
...
 
 #[cfg(not(any(feature = "std", feature = "libm")))]
 compile_error!("either the `std` or `libm` feature is required");
 
+#[cfg(not(any(feature = "chrono", feature = "jiff")))]
+compile_error!("either the `chrono` or `jiff` feature is required");
+
+// Besides for documentation, only one of the `chrono` or `jiff` features can be enabled
+#[cfg(all(not(doc), feature = "chrono", feature = "jiff"))]
+compile_error!("only one of the `chrono` or `jiff` features can be enabled");
```
Comment (ratmice) [inline src/lib.rs]: This really doesn't seem additive, in the sense that if you have some library crate `x`, which enables the `chrono` feature, and some library crate `y` which enables `jiff`, either would compile in isolation. But when you have a binary crate which depends on both the `x` and `y` crates, suddenly you would encounter this compilation error.

Is there a way to achieve what you want additively?

Comment (bim9262) [reply src/lib.rs]: Thanks for the feedback. I hadn't considered that case when putting together the PR. I think the only we to do it would be to have `SolarDay` (for chrono) and SolarDayJiff.

Ironically if the pattern for the `sunrise_sunset`  function had been kept (where it just takes floats/ints and returned ints) the the function signatures wouldn't have cause an issue with having multiple time libraries being specified.

Comment (ratmice) [reply src/lib.rs]: One thing I should say is I don't really see a way to make chrono optional, without a semver change, because even if you add a chrono feature, and make that feature `default`, and put the current usage behind a `#[cfg(feature = "chrono")]`.

There is a chance that people can use `default-features=false` while using `chrono`.
I guess what I would try is doing that, then adding `event_time_jiff`, maybe make `event_time` an alias for `event_time_chrono`?

note not actually a maintainer of this crate or anything.
Not sure how averse to semver breakage they might be.
This is a pretty minor breakage since it's very easy to fix just by enabling the chrono feature when using default-features = false.

Comment (remi-dupre) [reply src/lib.rs]: Hi!

Thanks for the contribution :)

Joining this conversation, it definitly feels like make chrono an optional feature would be the Rust way to go. It seems reasonable that it leads to a major version bump, handling another time library is definitly a big feature.

Comment (bim9262) [reply src/lib.rs]: Hello again, I know it's been a few months, but I just came across https://github.com/chronotope/chrono/issues/1768 and it jogged my memory of this PR. 

In light of chrono being soft-deprecated, would you consider a jiff-only implementation to supersede the chrono one?

Another idea I had would be to create a new type that can convert from chrono/jiff/etc, and then has a `to_chrono`, `to _jiff`, `to_etc`.

Comment (ratmice) [reply src/lib.rs]: I've not used jiff, in it's initial versions it's support for no `alloc` and `no_std` wasn't really supported.
From perusing through history, it *seems* like it's the case that this has basically been resolved.

Assuming that's the case I don't really have a problem with it, and it seems more straightforward than trying to have options enabling one or the other. But again that's merely my (mostly irrelevant) opinion.

Comment (bim9262) [reply src/lib.rs]: `jiff` should be  no `alloc` and `no_std` with the default features disabled.

File: src/lib.rs [hunk 2]
```diff
@@ -53,8 +56,9 @@ pub use crate::solar_equation::SolarDay;
 /// ```
 #[deprecated(
     since = "1.1.0",
-    note = "Use `SolarEvent` which is panic-free, more flexible and explicit."
+    note = "Use [`SolarDay`] which is panic-free, more flexible and explicit."
 )]
+#[cfg(feature = "chrono")]
```
Comment (bim9262) [inline src/lib.rs:61]: I didn't enable this deprecated function to work with `jiff`. Since this will be a breaking change (returning `crate::datetime::DateTime` instead of `chrono::Datetime`), it may be time to get rid of this function now that it will be several breaking versions beyond when it was deprecated.

File: src/datetime.rs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+    pub fn timestamp(&self) -> i64 {
+        self.0
+    }
+}
+
+#[cfg(feature = "chrono")]
+impl From<DateTime> for chrono::DateTime<chrono::Utc> {
+    fn from(dt: DateTime) -> Self {
+        chrono::DateTime::from_timestamp(dt.0, 0).expect("invalid result")
```
Comment (bim9262) [inline src/datetime.rs:17]: We should consider if  TryFrom would be a better fit so that we can return the errors.

Should also verify that the other expects can actually be thrown too.
